# **K-Nearest Neighbour Classifier**

In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

In [3]:
from sklearn.datasets import make_classification

In [4]:
X, y = make_classification(
    n_samples=1000,
    n_features=3,
    n_redundant=1,
    n_classes=2,
    random_state=999
)

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [7]:
from sklearn.neighbors import KNeighborsClassifier

In [10]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

for i in range(1, 10):
    classifier = KNeighborsClassifier(n_neighbors=i, algorithm='auto')
    classifier.fit(X_train, y_train)

    y_pred = classifier.predict(X_test)

    
    print(f"the {i} loop starts here:")
    print(confusion_matrix(y_pred, y_test))
    print(accuracy_score(y_pred, y_test))
    print(classification_report(y_pred, y_test))

the 1 loop starts here:
[[150  21]
 [ 19 140]]
0.8787878787878788
              precision    recall  f1-score   support

           0       0.89      0.88      0.88       171
           1       0.87      0.88      0.88       159

    accuracy                           0.88       330
   macro avg       0.88      0.88      0.88       330
weighted avg       0.88      0.88      0.88       330

the 2 loop starts here:
[[158  31]
 [ 11 130]]
0.8727272727272727
              precision    recall  f1-score   support

           0       0.93      0.84      0.88       189
           1       0.81      0.92      0.86       141

    accuracy                           0.87       330
   macro avg       0.87      0.88      0.87       330
weighted avg       0.88      0.87      0.87       330

the 3 loop starts here:
[[151  19]
 [ 18 142]]
0.8878787878787879
              precision    recall  f1-score   support

           0       0.89      0.89      0.89       170
           1       0.88      0.89      

## **7 is the best k value for this as we're getting 91.51% accuracy with that**